// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/status.proto

/*
Package status is a generated protocol buffer package.

It is generated from these files:
	proto/status.proto

It has these top-level messages:
	GetStatusRequest
	GetStatusResponse
*/
package status

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetStatusRequest struct {
}

func (m *GetStatusRequest) Reset()                    { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()               {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetStatusResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *GetStatusResponse) Reset()                    { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()               {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*GetStatusRequest)(nil), "status.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "status.GetStatusResponse")
}

func init() { proto.RegisterFile("proto/status.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0xd6, 0x03, 0x73, 0x84, 0xd8, 0x20, 0x3c, 0x25,
	0x21, 0x2e, 0x01, 0xf7, 0xd4, 0x92, 0x60, 0x30, 0x27, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44,
	0x49, 0x9b, 0x4b, 0x10, 0x49, 0xac, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x8c, 0x0b, 0xaa,
	0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xca, 0x33, 0x0a, 0xe6, 0xe2, 0x85, 0xa8, 0x0c,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x72, 0xe2, 0xe2, 0x84, 0xeb, 0x16, 0x92, 0xd0, 0x83,
	0xda, 0x8a, 0x6e, 0x89, 0x94, 0x24, 0x16, 0x19, 0x88, 0x55, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x47,
	0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x74, 0x41, 0x31, 0x4a, 0xba, 0x00, 0x00, 0x00,
}
